export const QUEST_VR_CONFIG = {
  maxVisibleNodes: 8000,
  farVisibleNodes: 3200,
  clusterCollapseDistanceMultiplier: 0.78,
  clusterDescendantBonus: 2,
  smoothMoveSpeed: 2.8,
  verticalMoveSpeed: 1.7,
  snapTurnAngle: Math.PI / 6,
  snapTurnDeadzone: 0.72,
  moveDeadzone: 0.18,
  rayLength: 180,
  hudDistance: 1.15,
  hudHeight: -0.03,
  hudWidth: 1.08,
  hudHeightWorld: 0.62,
  levelOverrides: {
    0: {
      visibleNodeBudget: 900,
      tileSize: 132,
      nodesPerTile: 1,
      nodeScale: 0.24,
      pickRadius: 28,
      showRelationshipEdges: false,
      clusterHiddenDescendants: true,
      clusterPositionsOnly: false,
    },
    1: {
      visibleNodeBudget: 2200,
      tileSize: 122,
      nodesPerTile: 1,
      nodeScale: 0.3,
      pickRadius: 26,
      showRelationshipEdges: false,
      clusterHiddenDescendants: true,
      clusterPositionsOnly: false,
    },
    2: {
      visibleNodeBudget: 4200,
      tileSize: 108,
      nodesPerTile: 2,
      nodeScale: 0.46,
      pickRadius: 24,
      showRelationshipEdges: false,
      clusterHiddenDescendants: true,
      clusterPositionsOnly: true,
    },
    3: {
      visibleNodeBudget: 6200,
      tileSize: 96,
      nodesPerTile: 3,
      nodeScale: 0.62,
      pickRadius: 22,
      showRelationshipEdges: true,
      clusterHiddenDescendants: true,
      clusterPositionsOnly: true,
    },
    4: {
      visibleNodeBudget: 8000,
      tileSize: 90,
      nodesPerTile: 4,
      nodeScale: 0.86,
      pickRadius: 20,
      showRelationshipEdges: true,
      clusterHiddenDescendants: true,
      clusterPositionsOnly: false,
    },
  },
};
